sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

addons:
  apt:
    packages:
      - slapd
      - ldap-utils

env:
  global:
    - TESTS_ZEND_LDAP_ONLINE_ENABLED=true
    - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
    - SITE_URL: https://zendframework.github.io/zend-ldap
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-ldap.git
    - secure: "oyutreHfOP5k3jQ3zZ28iJj64OSVCNqnCVfQrWnTDf3woV63vK0Le4X1O6WopAbd8yoEaN30nJ49X81zAUFN4lneulvitFHjEHvzNkOxFPWxfBK+APCnu0U0Z/a0BiFyoo1A5CGS3OrRpT1WL+CpTy49gpaqlfCnUVP/EnOP1uisKQIVQFbzoKl+0yAMzIXZ8rS5uFTej9lKbGi0V3+Gg896xXsmhLkb4ElNNNkccvB11cgDBLUarM43qL/s7kINv1uPbJ51WERujlZkcRH/s4OcYKPRREeDr+9aMZTELTuGFKLQKrhuA13YkHOSB/j6NnXEuEIVCpaVndrMXm69NBe/IfOuvSQoa4m0E7Ks6DZlX7nkj3rudlmX/+KakI+uJQdQLs7JDYKchuhX5hDO0dHGNTdwsPJAb06zDKR2HIfgzVZTX27//5PAKSU5DLOEM9sDYJAhQkxt0iC1L4xmQo/XOG8VNXL7usARouVI9FhmgPezmUDaN4CzvrD6kYtOVL3I9UwklnBQ0tJbO/CHnaq/eiWeNFL4tPDNim6c4pz9YayFQbOlu3SUy6lE/fwbXS1YtMl3t0MlO62B8wt+x0XlIJVTmMK0PFVj/cl93WUYZxxTZnFNvcy3VtmK7g6aNtHpAJaDQCl6Fu8K4xrWoTewG9m78KXu7p21gv9BjW8="

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
    - php: 7
      env:
        - TEST_COVERAGE=true
        - CHECK_CS=true
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: nightly
      env:
        - DEPS=lowest
    - php: nightly
      env:
        - DEPS=locked
    - php: nightly
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm 
      env:
        - DEPS=locked
    - php: hhvm 
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm
    - php: nightly

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false

before_install:
  - travis_retry composer self-update
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer require $COMPOSER_ARGS --dev --no-update "phpunit/phpunit:^4"; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require $COMPOSER_ARGS --dev satooshi/php-coveralls ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show --installed

before_script:
  - phpenv config-add .ci/php.ini || return 0
  - .ci/OpenLDAP_run.sh
  - .ci/load_fixtures.sh

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; fi
  - if [[ $TEST_COVERAGE != 'true' ]]; then composer test ; fi
  - if [[ $CHECK_CS == 'true' ]]; then composer cs-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi


after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer upload-coverage ; fi
